### ISSUE TITLE
带atall的推送无法发出，报错{'code': 5, 'msg': '指定对象不存在'}

### ISSUE THREAD

**Issue by fall2wish** [Starlwr/StarBot#22]
检查了群号没有问题，其他不太看得出来
2024-10-15 21:21:09.146 | INFO     | starbot.core.room:204 | [开播] 黛尔菲娜_Delphine (30176136)
2024-10-15 21:21:17.738 | INFO     | starbot.core.sender:172 | 2214438158 -> 群[807518260] : @全体成员 黛尔菲娜_Delphine 正在直播 【四语歌势】周二悲伤抓鬼\nhttps://live.bilibili.com/30176136[图片]
2024-10-15 21:21:17.807 | ERROR    | graia.ariadne.util:126 | Task exception was never retrieved
future: <Task finished name='Task-39776' coro=<Up.connect.<locals>.live_on() done, defined at /root/venvstarbot/lib/python3.10/site-packages/starbot/core/room.py:177> exception=UnknownTarget('对象位置未知, 不存在或不可及.', {'code': 5, 'msg': '指定对象不存在'})>
Traceback (most recent call last):

> File "/root/venvstarbot/lib/python3.10/site-packages/starbot/core/room.py", line 250, in live_on
    await self.__bot.send_live_on_at(self)
          │                          └ Up(uid=3494369332038563, targets=[PushTarget(id=2735642380, type=<PushType.Friend: 0>, live_on=LiveOn(enabled=False, message=...
          └ Up(uid=3494369332038563, targets=[PushTarget(id=2735642380, type=<PushType.Friend: 0>, live_on=LiveOn(enabled=False, message=...
  File "/root/venvstarbot/lib/python3.10/site-packages/starbot/core/sender.py", line 349, in send_live_on_at
    bot_info = await self.__bot.get_member(target.id, self.qq)
                     │                     │      │   │    └ 2214438158
                     │                     │      │   └ Bot(qq=2214438158, ups=[Up(uid=3494369332038563, targets=[PushTarget(id=2735642380, type=<PushType.Friend: 0>, live_on=LiveOn...
                     │                     │      └ 870139435
                     │                     └ PushTarget(id=870139435, type=<PushType.Group: 1>, live_on=LiveOn(enabled=True, message='{atall} {uname} 正在直播 {title}\n{url}{...
                     └ Bot(qq=2214438158, ups=[Up(uid=3494369332038563, targets=[PushTarget(id=2735642380, type=<PushType.Friend: 0>, live_on=LiveOn...
  File "/root/venvstarbot/lib/python3.10/site-packages/graia/ariadne/app.py", line 1459, in get_member
    await self.connection.call(
          │    │          └ <function ConnectionInterface.call at 0x7fac4b1fc0>
          │    └ <graia.ariadne.connection.ConnectionInterface object at 0x7f881ef3d0>
          └ <graia.ariadne.app.Ariadne object at 0x7f881eddb0>
  File "/root/venvstarbot/lib/python3.10/site-packages/graia/ariadne/connection/__init__.py", line 202, in call
    return await connection.call(command, method, params, in_session=in_session)
                 │          │    │        │       │                  └ True
                 │          │    │        │       └ {'target': 870139435, 'memberId': 2214438158}
                 │          │    │        └ <CallMethod.RESTGET: 'get'>
                 │          │    └ 'memberInfo'
                 │          └ <function WebsocketConnectionMixin.call at 0x7fac4b1870>
                 └ <WebsocketClientConnection <ConnectionStatus connected=True alive=True verified=True stage=blocking> with 2 callbacks>
  File "/root/venvstarbot/lib/python3.10/site-packages/graia/ariadne/connection/ws.py", line 116, in call
    return await fut
                 └ <Future finished exception=UnknownTarget('对象位置未知, 不存在或不可及.', {'code': 5, 'msg': '指定对象不存在'})>

graia.ariadne.exception.UnknownTarget: ('对象位置未知, 不存在或不可及.', {'code': 5, 'msg': '指定对象不存在'})

**Comment by Starlwr** [comment]
是用的nt吧

**Comment by Book-fall2wish** [comment]
> 是用的nt吧

mirai的overflow连napcat

**Comment by Starlwr** [comment]
那边获取bot本身的信息可能有点问题，mirai目前正常

**Comment by Book-fall2wish** [comment]
> 那边获取bot本身的信息可能有点问题，mirai目前正常

好像是一样的消息发太多导致风控了
